---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eliteapp-deployment
  labels:
    app: eliteapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eliteapp
  template:
    metadata:
      labels:
        app: eliteapp
    spec:
      containers:
        - name: eliteapp
          image: devops1117/eliteapp:v10
          ports:
            - containerPort: 80
